name: Build & Test

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up NPM
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: npm i # Install dependencies
      - run: npm run build # Build sources
      - run: npm test # Run tests
